# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smooth-ios' do
  use_frameworks!
  pod 'SnapKit'
  pod 'Then'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'MoyaSugar'
  

end
